 --DROP TABLE IF EXISTS user;
 
 --CREATE TABLE user (
 --id INTEGER PRIMARY KEY AUTOINCREMENT,
 --username TEXT UNIQUE NOT NULL,
 --password TEXT NOT NULL,
 --firstname TEXT NOT NULL,
 --lastname TEXT NOT NULL,
 --gender TEXT NOT NULL,
 --dob TEXT NOT NULL,
 --worker_id TEXT NOT NULL,
 --divisionInput TEXT NOT NULL,
 --officeInput TEXT NOT NULL,
 --unitInput TEXT NOT NULL
 --);