 --DROP TABLE IF EXISTS user;
 
 CREATE TABLE user (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT UNIQUE NOT NULL,
 password TEXT NOT NULL,
 firstname TEXT NOT NULL,
 lastname TEXT NOT NULL,
 gender TEXT NOT NULL,
 dob TEXT NOT NULL,
 address1 TEXT NOT NULL,
 address1 TEXT NOT NULL,
 postcode TEXT NOT NULL,
 area TEXT NOT NULL,
 state TEXT NOT NULL,
 );